#!/bin/bash

# Demo for using color codes in your scripts

#------------------------------------------////
# 	  Loop to list all the color codes:
#------------------------------------------////

for c in {0..255}; do
tput setaf "${c}"; tput setaf "${c}" | command cat -v; printf "%b\n" "     ###### tput code ###### "${c}"";
done

#------------------------------------------////
#	Assign the "color name" as a variable:
# 	Change Color Numbers to your liking:
#------------------------------------------////

white=$(tput setaf 15)
black=$(tput setaf 16)
gray=$(tput setaf 240)
blue=$(tput setaf 21)
green=$(tput setaf 34)
red=$(tput setaf 1)
cyan=$(tput setaf 36)
purple=$(tput setaf 128)
brown=$(tput setaf 130)
yellow=$(tput setaf 226)
orange=$(tput setaf 202)
lgray=$(tput setaf 246)
lblue=$(tput setaf 39)
lgreen=$(tput setaf 118)
lcyan=$(tput setaf 14)
lred=$(tput setaf 9)
lpurple=$(tput setaf 99)
normal=$(tput sgr0)
blink=$(tput blink)

#------------------------------------------////
# 			Array with Variables:
#------------------------------------------////

array=(
"${white}" "############	 White	 	############ "${black}" <----- White\n"
"${black}" "############	 Black	 	############ "${white}" <----- Black\n"
"${gray}"  "############	 Gray	 	############\n"
"${blue}"  "############	 Blue	 	############\n"
"${green}" "############	 Green	 	############\n"
"${red}"   "############	 Red	 	############\n"
"${cyan}"  "############	 Cyan	 	############\n"
"${purple}" "############	 Purple	 	############\n"
"${brown}" "############	 Brown	 	############\n"
"${yellow}" "############	 Yellow	 	############\n"
"${orange}" "############	 Orange   	############\n"
"${lgray}" "############	 Light Gray	############\n"
"${lblue}" "############	 Light Blue	############\n"
"${lgreen}" "############	 Light Green    ############\n"
"${lcyan}" "############	 Light Cyan	############\n"
"${lred}"  "############	 Light Red	############\n"
"${lpurple}" "############	 Light Purple   ############\n"
"${normal}" "############	 Normal	 	############\n"
"${red}"   "############ ${white}${blink}    Blink${normal}	 	${blue}############\n"
)

#------------------------------------------////
#		Print the Array for Demo:
#------------------------------------------////
printf "%b\n" "${blue}"
command cat <<"EOF"
  ____ ___  _     ___  ____      ____  _____ __  __  ___  
 / ___/ _ \| |   / _ \|  _ \    |  _ \| ____|  \/  |/ _ \ 
| |  | | | | |  | | | | |_) |   | | | |  _| | |\/| | | | |
| |__| |_| | |__| |_| |  _ <    | |_| | |___| |  | | |_| |
 \____\___/|_____\___/|_| \_\   |____/|_____|_|  |_|\___/ 
                                                          
EOF
printf "%b\n" "${normal}"
printf "%b" "${array[@]}"
printf "%b" "${normal}" "\n"

#------------------------------------------////
# Print as a single line
# Like you might use in a script:
#------------------------------------------////

printf "%b" "${red}" "      Combine colors "${white}"on the"${blue}" same line \n\n"
#printf "%b\n"
